// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: likes.sql

package sqlcgen

import (
	"context"
	"time"
)

const insertLike = `-- name: InsertLike :exec
INSERT INTO dating_likes (id, from_user_id, to_user_id, created_at) VALUES ($1, $2, $3, $4)
`

type InsertLikeParams struct {
	ID         string
	FromUserID string
	ToUserID   string
	CreatedAt  time.Time
}

func (q *Queries) InsertLike(ctx context.Context, arg InsertLikeParams) error {
	_, err := q.db.Exec(ctx, insertLike,
		arg.ID,
		arg.FromUserID,
		arg.ToUserID,
		arg.CreatedAt,
	)
	return err
}

const likeExists = `-- name: LikeExists :one
SELECT EXISTS (SELECT 1 FROM dating_likes WHERE from_user_id = $1 AND to_user_id = $2) AS exists
`

type LikeExistsParams struct {
	FromUserID string
	ToUserID   string
}

func (q *Queries) LikeExists(ctx context.Context, arg LikeExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, likeExists, arg.FromUserID, arg.ToUserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listLikesByFromUser = `-- name: ListLikesByFromUser :many
SELECT id, from_user_id, to_user_id, created_at FROM dating_likes WHERE from_user_id = $1 ORDER BY created_at DESC, id
`

func (q *Queries) ListLikesByFromUser(ctx context.Context, fromUserID string) ([]DatingLike, error) {
	rows, err := q.db.Query(ctx, listLikesByFromUser, fromUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DatingLike{}
	for rows.Next() {
		var i DatingLike
		if err := rows.Scan(
			&i.ID,
			&i.FromUserID,
			&i.ToUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLikesByToUser = `-- name: ListLikesByToUser :many
SELECT id, from_user_id, to_user_id, created_at FROM dating_likes WHERE to_user_id = $1 ORDER BY created_at DESC, id
`

func (q *Queries) ListLikesByToUser(ctx context.Context, toUserID string) ([]DatingLike, error) {
	rows, err := q.db.Query(ctx, listLikesByToUser, toUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DatingLike{}
	for rows.Next() {
		var i DatingLike
		if err := rows.Scan(
			&i.ID,
			&i.FromUserID,
			&i.ToUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
