// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: matches.sql

package sqlcgen

import (
	"context"
	"time"
)

const insertMatch = `-- name: InsertMatch :exec
INSERT INTO dating_matches (id, user_id_a, user_id_b, score, breakdown, matched_at) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertMatchParams struct {
	ID        string
	UserIDA   string
	UserIDB   string
	Score     float64
	Breakdown []byte
	MatchedAt time.Time
}

func (q *Queries) InsertMatch(ctx context.Context, arg InsertMatchParams) error {
	_, err := q.db.Exec(ctx, insertMatch,
		arg.ID,
		arg.UserIDA,
		arg.UserIDB,
		arg.Score,
		arg.Breakdown,
		arg.MatchedAt,
	)
	return err
}

const listMatchesByUser = `-- name: ListMatchesByUser :many
SELECT id, user_id_a, user_id_b, score, breakdown, matched_at
FROM dating_matches
WHERE user_id_a = $1 OR user_id_b = $1
ORDER BY matched_at DESC, id
`

func (q *Queries) ListMatchesByUser(ctx context.Context, userIDA string) ([]DatingMatch, error) {
	rows, err := q.db.Query(ctx, listMatchesByUser, userIDA)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DatingMatch{}
	for rows.Next() {
		var i DatingMatch
		if err := rows.Scan(
			&i.ID,
			&i.UserIDA,
			&i.UserIDB,
			&i.Score,
			&i.Breakdown,
			&i.MatchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMutualMatchesByUser = `-- name: ListMutualMatchesByUser :many
SELECT m.id, m.user_id_a, m.user_id_b, m.score, m.breakdown, m.matched_at
FROM dating_matches m
WHERE (m.user_id_a = $1 OR m.user_id_b = $1)
  AND EXISTS (SELECT 1 FROM dating_likes l WHERE l.from_user_id = m.user_id_a AND l.to_user_id = m.user_id_b)
  AND EXISTS (SELECT 1 FROM dating_likes l WHERE l.from_user_id = m.user_id_b AND l.to_user_id = m.user_id_a)
ORDER BY m.matched_at DESC, m.id
`

func (q *Queries) ListMutualMatchesByUser(ctx context.Context, userIDA string) ([]DatingMatch, error) {
	rows, err := q.db.Query(ctx, listMutualMatchesByUser, userIDA)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DatingMatch{}
	for rows.Next() {
		var i DatingMatch
		if err := rows.Scan(
			&i.ID,
			&i.UserIDA,
			&i.UserIDB,
			&i.Score,
			&i.Breakdown,
			&i.MatchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
