// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: preferences.sql

package sqlcgen

import (
	"context"
)

const deletePreferenceDrinkingStatuses = `-- name: DeletePreferenceDrinkingStatuses :exec
DELETE FROM dating_preference_drinking_statuses WHERE user_id = $1
`

func (q *Queries) DeletePreferenceDrinkingStatuses(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deletePreferenceDrinkingStatuses, userID)
	return err
}

const deletePreferenceEducations = `-- name: DeletePreferenceEducations :exec
DELETE FROM dating_preference_educations WHERE user_id = $1
`

func (q *Queries) DeletePreferenceEducations(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deletePreferenceEducations, userID)
	return err
}

const deletePreferenceMarriageDesires = `-- name: DeletePreferenceMarriageDesires :exec
DELETE FROM dating_preference_marriage_desires WHERE user_id = $1
`

func (q *Queries) DeletePreferenceMarriageDesires(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deletePreferenceMarriageDesires, userID)
	return err
}

const deletePreferencePrefectures = `-- name: DeletePreferencePrefectures :exec
DELETE FROM dating_preference_prefectures WHERE user_id = $1
`

func (q *Queries) DeletePreferencePrefectures(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deletePreferencePrefectures, userID)
	return err
}

const deletePreferenceSmokingStatuses = `-- name: DeletePreferenceSmokingStatuses :exec
DELETE FROM dating_preference_smoking_statuses WHERE user_id = $1
`

func (q *Queries) DeletePreferenceSmokingStatuses(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deletePreferenceSmokingStatuses, userID)
	return err
}

const getPreference = `-- name: GetPreference :one
SELECT user_id, age_min, age_max, height_min, height_max, income_min, updated_at
FROM dating_preferences
WHERE user_id = $1
`

func (q *Queries) GetPreference(ctx context.Context, userID string) (DatingPreference, error) {
	row := q.db.QueryRow(ctx, getPreference, userID)
	var i DatingPreference
	err := row.Scan(
		&i.UserID,
		&i.AgeMin,
		&i.AgeMax,
		&i.HeightMin,
		&i.HeightMax,
		&i.IncomeMin,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPreferenceDrinkingStatus = `-- name: InsertPreferenceDrinkingStatus :one
INSERT INTO dating_preference_drinking_statuses (user_id, drinking_status) VALUES ($1, $2) RETURNING id
`

type InsertPreferenceDrinkingStatusParams struct {
	UserID         string
	DrinkingStatus string
}

func (q *Queries) InsertPreferenceDrinkingStatus(ctx context.Context, arg InsertPreferenceDrinkingStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertPreferenceDrinkingStatus, arg.UserID, arg.DrinkingStatus)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPreferenceEducation = `-- name: InsertPreferenceEducation :one
INSERT INTO dating_preference_educations (user_id, education) VALUES ($1, $2) RETURNING id
`

type InsertPreferenceEducationParams struct {
	UserID    string
	Education string
}

func (q *Queries) InsertPreferenceEducation(ctx context.Context, arg InsertPreferenceEducationParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertPreferenceEducation, arg.UserID, arg.Education)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPreferenceMarriageDesire = `-- name: InsertPreferenceMarriageDesire :one
INSERT INTO dating_preference_marriage_desires (user_id, marriage_desire) VALUES ($1, $2) RETURNING id
`

type InsertPreferenceMarriageDesireParams struct {
	UserID         string
	MarriageDesire string
}

func (q *Queries) InsertPreferenceMarriageDesire(ctx context.Context, arg InsertPreferenceMarriageDesireParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertPreferenceMarriageDesire, arg.UserID, arg.MarriageDesire)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPreferencePrefecture = `-- name: InsertPreferencePrefecture :one
INSERT INTO dating_preference_prefectures (user_id, prefecture) VALUES ($1, $2) RETURNING id
`

type InsertPreferencePrefectureParams struct {
	UserID     string
	Prefecture string
}

func (q *Queries) InsertPreferencePrefecture(ctx context.Context, arg InsertPreferencePrefectureParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertPreferencePrefecture, arg.UserID, arg.Prefecture)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPreferenceSmokingStatus = `-- name: InsertPreferenceSmokingStatus :one
INSERT INTO dating_preference_smoking_statuses (user_id, smoking_status) VALUES ($1, $2) RETURNING id
`

type InsertPreferenceSmokingStatusParams struct {
	UserID        string
	SmokingStatus string
}

func (q *Queries) InsertPreferenceSmokingStatus(ctx context.Context, arg InsertPreferenceSmokingStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertPreferenceSmokingStatus, arg.UserID, arg.SmokingStatus)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listPreferenceDrinkingStatuses = `-- name: ListPreferenceDrinkingStatuses :many
SELECT id, user_id, drinking_status FROM dating_preference_drinking_statuses WHERE user_id = $1 ORDER BY id
`

func (q *Queries) ListPreferenceDrinkingStatuses(ctx context.Context, userID string) ([]DatingPreferenceDrinkingStatus, error) {
	rows, err := q.db.Query(ctx, listPreferenceDrinkingStatuses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DatingPreferenceDrinkingStatus{}
	for rows.Next() {
		var i DatingPreferenceDrinkingStatus
		if err := rows.Scan(&i.ID, &i.UserID, &i.DrinkingStatus); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPreferenceEducations = `-- name: ListPreferenceEducations :many
SELECT id, user_id, education FROM dating_preference_educations WHERE user_id = $1 ORDER BY id
`

func (q *Queries) ListPreferenceEducations(ctx context.Context, userID string) ([]DatingPreferenceEducation, error) {
	rows, err := q.db.Query(ctx, listPreferenceEducations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DatingPreferenceEducation{}
	for rows.Next() {
		var i DatingPreferenceEducation
		if err := rows.Scan(&i.ID, &i.UserID, &i.Education); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPreferenceMarriageDesires = `-- name: ListPreferenceMarriageDesires :many
SELECT id, user_id, marriage_desire FROM dating_preference_marriage_desires WHERE user_id = $1 ORDER BY id
`

func (q *Queries) ListPreferenceMarriageDesires(ctx context.Context, userID string) ([]DatingPreferenceMarriageDesire, error) {
	rows, err := q.db.Query(ctx, listPreferenceMarriageDesires, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DatingPreferenceMarriageDesire{}
	for rows.Next() {
		var i DatingPreferenceMarriageDesire
		if err := rows.Scan(&i.ID, &i.UserID, &i.MarriageDesire); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPreferencePrefectures = `-- name: ListPreferencePrefectures :many
SELECT id, user_id, prefecture FROM dating_preference_prefectures WHERE user_id = $1 ORDER BY id
`

func (q *Queries) ListPreferencePrefectures(ctx context.Context, userID string) ([]DatingPreferencePrefecture, error) {
	rows, err := q.db.Query(ctx, listPreferencePrefectures, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DatingPreferencePrefecture{}
	for rows.Next() {
		var i DatingPreferencePrefecture
		if err := rows.Scan(&i.ID, &i.UserID, &i.Prefecture); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPreferenceSmokingStatuses = `-- name: ListPreferenceSmokingStatuses :many
SELECT id, user_id, smoking_status FROM dating_preference_smoking_statuses WHERE user_id = $1 ORDER BY id
`

func (q *Queries) ListPreferenceSmokingStatuses(ctx context.Context, userID string) ([]DatingPreferenceSmokingStatus, error) {
	rows, err := q.db.Query(ctx, listPreferenceSmokingStatuses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DatingPreferenceSmokingStatus{}
	for rows.Next() {
		var i DatingPreferenceSmokingStatus
		if err := rows.Scan(&i.ID, &i.UserID, &i.SmokingStatus); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPreference = `-- name: UpsertPreference :exec
INSERT INTO dating_preferences (user_id, age_min, age_max, height_min, height_max, income_min, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (user_id) DO UPDATE SET
  age_min = EXCLUDED.age_min,
  age_max = EXCLUDED.age_max,
  height_min = EXCLUDED.height_min,
  height_max = EXCLUDED.height_max,
  income_min = EXCLUDED.income_min,
  updated_at = now()
`

type UpsertPreferenceParams struct {
	UserID    string
	AgeMin    *int32
	AgeMax    *int32
	HeightMin *int32
	HeightMax *int32
	IncomeMin *int32
}

func (q *Queries) UpsertPreference(ctx context.Context, arg UpsertPreferenceParams) error {
	_, err := q.db.Exec(ctx, upsertPreference,
		arg.UserID,
		arg.AgeMin,
		arg.AgeMax,
		arg.HeightMin,
		arg.HeightMax,
		arg.IncomeMin,
	)
	return err
}
