// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package sqlcgen

import (
	"context"
)

const getProfile = `-- name: GetProfile :one
SELECT user_id, height, body_type, education, occupation, income_level, marriage_desire, children_desire, smoking, drinking, self_introduction, updated_at
FROM dating_profiles
WHERE user_id = $1
`

func (q *Queries) GetProfile(ctx context.Context, userID string) (DatingProfile, error) {
	row := q.db.QueryRow(ctx, getProfile, userID)
	var i DatingProfile
	err := row.Scan(
		&i.UserID,
		&i.Height,
		&i.BodyType,
		&i.Education,
		&i.Occupation,
		&i.IncomeLevel,
		&i.MarriageDesire,
		&i.ChildrenDesire,
		&i.Smoking,
		&i.Drinking,
		&i.SelfIntroduction,
		&i.UpdatedAt,
	)
	return i, err
}

const listProfilePhotos = `-- name: ListProfilePhotos :many
SELECT id, user_id, url, is_primary, display_order, created_at FROM dating_profile_photos WHERE user_id = $1 ORDER BY display_order, id
`

func (q *Queries) ListProfilePhotos(ctx context.Context, userID string) ([]DatingProfilePhoto, error) {
	rows, err := q.db.Query(ctx, listProfilePhotos, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DatingProfilePhoto{}
	for rows.Next() {
		var i DatingProfilePhoto
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			&i.IsPrimary,
			&i.DisplayOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfileTags = `-- name: ListProfileTags :many
SELECT id, user_id, tag FROM dating_profile_tags WHERE user_id = $1 ORDER BY id
`

func (q *Queries) ListProfileTags(ctx context.Context, userID string) ([]DatingProfileTag, error) {
	rows, err := q.db.Query(ctx, listProfileTags, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DatingProfileTag{}
	for rows.Next() {
		var i DatingProfileTag
		if err := rows.Scan(&i.ID, &i.UserID, &i.Tag); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProfile = `-- name: UpsertProfile :exec
INSERT INTO dating_profiles (user_id, height, body_type, education, occupation, income_level, marriage_desire, children_desire, smoking, drinking, self_introduction, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, now())
ON CONFLICT (user_id) DO UPDATE SET
  height = EXCLUDED.height,
  body_type = EXCLUDED.body_type,
  education = EXCLUDED.education,
  occupation = EXCLUDED.occupation,
  income_level = EXCLUDED.income_level,
  marriage_desire = EXCLUDED.marriage_desire,
  children_desire = EXCLUDED.children_desire,
  smoking = EXCLUDED.smoking,
  drinking = EXCLUDED.drinking,
  self_introduction = EXCLUDED.self_introduction,
  updated_at = now()
`

type UpsertProfileParams struct {
	UserID           string
	Height           *int32
	BodyType         *string
	Education        *string
	Occupation       *string
	IncomeLevel      *int32
	MarriageDesire   *string
	ChildrenDesire   *string
	Smoking          *string
	Drinking         *string
	SelfIntroduction *string
}

func (q *Queries) UpsertProfile(ctx context.Context, arg UpsertProfileParams) error {
	_, err := q.db.Exec(ctx, upsertProfile,
		arg.UserID,
		arg.Height,
		arg.BodyType,
		arg.Education,
		arg.Occupation,
		arg.IncomeLevel,
		arg.MarriageDesire,
		arg.ChildrenDesire,
		arg.Smoking,
		arg.Drinking,
		arg.SelfIntroduction,
	)
	return err
}
