// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO dating_users (id, nickname, gender, birth_date, prefecture, verified, elo_rating, created_at, last_active_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateUserParams struct {
	ID           string
	Nickname     string
	Gender       string
	BirthDate    time.Time
	Prefecture   string
	Verified     bool
	EloRating    int32
	CreatedAt    time.Time
	LastActiveAt time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Nickname,
		arg.Gender,
		arg.BirthDate,
		arg.Prefecture,
		arg.Verified,
		arg.EloRating,
		arg.CreatedAt,
		arg.LastActiveAt,
	)
	return err
}

const findCandidateUsers = `-- name: FindCandidateUsers :many
SELECT u.id, u.nickname, u.gender, u.birth_date, u.prefecture, u.verified, u.elo_rating, u.created_at, u.last_active_at
FROM dating_users u
INNER JOIN dating_profiles p ON p.user_id = u.id
WHERE u.id <> $1
  AND u.verified = TRUE
  AND ($2::date IS NULL OR u.birth_date >= $2::date)
  AND ($3::date IS NULL OR u.birth_date <= $3::date)
  AND (cardinality($4::text[]) = 0 OR u.prefecture = ANY($4::text[]))
  AND ($5::int IS NULL OR p.height >= $5::int)
  AND ($6::int IS NULL OR p.height <= $6::int)
  AND ($7::int IS NULL OR p.income_level >= $7::int)
  AND (cardinality($8::text[]) = 0 OR p.education = ANY($8::text[]))
  AND (cardinality($9::text[]) = 0 OR p.marriage_desire = ANY($9::text[]))
  AND (cardinality($10::text[]) = 0 OR p.smoking = ANY($10::text[]))
  AND (cardinality($11::text[]) = 0 OR p.drinking = ANY($11::text[]))
ORDER BY u.id
LIMIT 1000
`

type FindCandidateUsersParams struct {
	UserID           string
	BirthMin         *time.Time
	BirthMax         *time.Time
	Prefectures      []string
	HeightMin        *int32
	HeightMax        *int32
	IncomeMin        *int32
	Educations       []string
	MarriageDesires  []string
	SmokingStatuses  []string
	DrinkingStatuses []string
}

// 認証済みユーザーのうち、プロフィールを持ち条件に合う候補を最大1000件返す。
// 各条件は NULL または空配列のとき無視する。
func (q *Queries) FindCandidateUsers(ctx context.Context, arg FindCandidateUsersParams) ([]DatingUser, error) {
	rows, err := q.db.Query(ctx, findCandidateUsers,
		arg.UserID,
		arg.BirthMin,
		arg.BirthMax,
		arg.Prefectures,
		arg.HeightMin,
		arg.HeightMax,
		arg.IncomeMin,
		arg.Educations,
		arg.MarriageDesires,
		arg.SmokingStatuses,
		arg.DrinkingStatuses,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DatingUser{}
	for rows.Next() {
		var i DatingUser
		if err := rows.Scan(
			&i.ID,
			&i.Nickname,
			&i.Gender,
			&i.BirthDate,
			&i.Prefecture,
			&i.Verified,
			&i.EloRating,
			&i.CreatedAt,
			&i.LastActiveAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, nickname, gender, birth_date, prefecture, verified, elo_rating, created_at, last_active_at
FROM dating_users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id string) (DatingUser, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i DatingUser
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.Gender,
		&i.BirthDate,
		&i.Prefecture,
		&i.Verified,
		&i.EloRating,
		&i.CreatedAt,
		&i.LastActiveAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE dating_users
SET nickname = $2, gender = $3, birth_date = $4, prefecture = $5, verified = $6, elo_rating = $7, last_active_at = $8
WHERE id = $1
`

type UpdateUserParams struct {
	ID           string
	Nickname     string
	Gender       string
	BirthDate    time.Time
	Prefecture   string
	Verified     bool
	EloRating    int32
	LastActiveAt time.Time
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Nickname,
		arg.Gender,
		arg.BirthDate,
		arg.Prefecture,
		arg.Verified,
		arg.EloRating,
		arg.LastActiveAt,
	)
	return err
}
