// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: companies.sql

package sqlcgen

import (
	"context"
	"time"
)

const createCompany = `-- name: CreateCompany :exec
INSERT INTO ma_companies (id, name, industry, location, employee_count, founded, listing_status, matching_purpose, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateCompanyParams struct {
	ID              string
	Name            string
	Industry        string
	Location        string
	EmployeeCount   int32
	Founded         time.Time
	ListingStatus   string
	MatchingPurpose string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) error {
	_, err := q.db.Exec(ctx, createCompany,
		arg.ID,
		arg.Name,
		arg.Industry,
		arg.Location,
		arg.EmployeeCount,
		arg.Founded,
		arg.ListingStatus,
		arg.MatchingPurpose,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteCriteriaIndustries = `-- name: DeleteCriteriaIndustries :exec
DELETE FROM ma_criteria_industries WHERE company_id = $1
`

func (q *Queries) DeleteCriteriaIndustries(ctx context.Context, companyID string) error {
	_, err := q.db.Exec(ctx, deleteCriteriaIndustries, companyID)
	return err
}

const getCompany = `-- name: GetCompany :one
SELECT id, name, industry, location, employee_count, founded, listing_status, matching_purpose, created_at, updated_at
FROM ma_companies
WHERE id = $1
`

func (q *Queries) GetCompany(ctx context.Context, id string) (MaCompany, error) {
	row := q.db.QueryRow(ctx, getCompany, id)
	var i MaCompany
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Industry,
		&i.Location,
		&i.EmployeeCount,
		&i.Founded,
		&i.ListingStatus,
		&i.MatchingPurpose,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCriteria = `-- name: GetCriteria :one
SELECT company_id, purpose, revenue_min, revenue_max, ebitda_min, employee_min, employee_max, max_debt_equity_ratio, updated_at
FROM ma_matching_criteria
WHERE company_id = $1
`

func (q *Queries) GetCriteria(ctx context.Context, companyID string) (MaMatchingCriterium, error) {
	row := q.db.QueryRow(ctx, getCriteria, companyID)
	var i MaMatchingCriterium
	err := row.Scan(
		&i.CompanyID,
		&i.Purpose,
		&i.RevenueMin,
		&i.RevenueMax,
		&i.EbitdaMin,
		&i.EmployeeMin,
		&i.EmployeeMax,
		&i.MaxDebtEquityRatio,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCompanyMarket = `-- name: InsertCompanyMarket :one
INSERT INTO ma_company_markets (company_id, market) VALUES ($1, $2) RETURNING id
`

type InsertCompanyMarketParams struct {
	CompanyID string
	Market    string
}

func (q *Queries) InsertCompanyMarket(ctx context.Context, arg InsertCompanyMarketParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertCompanyMarket, arg.CompanyID, arg.Market)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertCompanyTechnology = `-- name: InsertCompanyTechnology :one
INSERT INTO ma_company_technologies (company_id, technology) VALUES ($1, $2) RETURNING id
`

type InsertCompanyTechnologyParams struct {
	CompanyID  string
	Technology string
}

func (q *Queries) InsertCompanyTechnology(ctx context.Context, arg InsertCompanyTechnologyParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertCompanyTechnology, arg.CompanyID, arg.Technology)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertCriteriaIndustry = `-- name: InsertCriteriaIndustry :one
INSERT INTO ma_criteria_industries (company_id, industry) VALUES ($1, $2) RETURNING id
`

type InsertCriteriaIndustryParams struct {
	CompanyID string
	Industry  string
}

func (q *Queries) InsertCriteriaIndustry(ctx context.Context, arg InsertCriteriaIndustryParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertCriteriaIndustry, arg.CompanyID, arg.Industry)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listCompaniesByPurpose = `-- name: ListCompaniesByPurpose :many
SELECT id, name, industry, location, employee_count, founded, listing_status, matching_purpose, created_at, updated_at
FROM ma_companies
WHERE matching_purpose = $1
  AND (cardinality($2::text[]) = 0 OR industry = ANY($2::text[]))
  AND ($3::int IS NULL OR employee_count >= $3::int)
  AND ($4::int IS NULL OR employee_count <= $4::int)
ORDER BY id
LIMIT 500
`

type ListCompaniesByPurposeParams struct {
	Purpose     string
	Industries  []string
	EmployeeMin *int32
	EmployeeMax *int32
}

// 目的が一致する企業を最大500件返す。業種配列が空、従業員条件が NULL のときは無視する。
func (q *Queries) ListCompaniesByPurpose(ctx context.Context, arg ListCompaniesByPurposeParams) ([]MaCompany, error) {
	rows, err := q.db.Query(ctx, listCompaniesByPurpose,
		arg.Purpose,
		arg.Industries,
		arg.EmployeeMin,
		arg.EmployeeMax,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaCompany{}
	for rows.Next() {
		var i MaCompany
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Industry,
			&i.Location,
			&i.EmployeeCount,
			&i.Founded,
			&i.ListingStatus,
			&i.MatchingPurpose,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompanyMarkets = `-- name: ListCompanyMarkets :many
SELECT id, company_id, market FROM ma_company_markets WHERE company_id = $1 ORDER BY id
`

func (q *Queries) ListCompanyMarkets(ctx context.Context, companyID string) ([]MaCompanyMarket, error) {
	rows, err := q.db.Query(ctx, listCompanyMarkets, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaCompanyMarket{}
	for rows.Next() {
		var i MaCompanyMarket
		if err := rows.Scan(&i.ID, &i.CompanyID, &i.Market); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompanyTechnologies = `-- name: ListCompanyTechnologies :many
SELECT id, company_id, technology FROM ma_company_technologies WHERE company_id = $1 ORDER BY id
`

func (q *Queries) ListCompanyTechnologies(ctx context.Context, companyID string) ([]MaCompanyTechnology, error) {
	rows, err := q.db.Query(ctx, listCompanyTechnologies, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaCompanyTechnology{}
	for rows.Next() {
		var i MaCompanyTechnology
		if err := rows.Scan(&i.ID, &i.CompanyID, &i.Technology); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCriteriaIndustries = `-- name: ListCriteriaIndustries :many
SELECT id, company_id, industry FROM ma_criteria_industries WHERE company_id = $1 ORDER BY id
`

func (q *Queries) ListCriteriaIndustries(ctx context.Context, companyID string) ([]MaCriteriaIndustry, error) {
	rows, err := q.db.Query(ctx, listCriteriaIndustries, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaCriteriaIndustry{}
	for rows.Next() {
		var i MaCriteriaIndustry
		if err := rows.Scan(&i.ID, &i.CompanyID, &i.Industry); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompany = `-- name: UpdateCompany :exec
UPDATE ma_companies
SET name = $2, industry = $3, location = $4, employee_count = $5, founded = $6, listing_status = $7, matching_purpose = $8, updated_at = now()
WHERE id = $1
`

type UpdateCompanyParams struct {
	ID              string
	Name            string
	Industry        string
	Location        string
	EmployeeCount   int32
	Founded         time.Time
	ListingStatus   string
	MatchingPurpose string
}

func (q *Queries) UpdateCompany(ctx context.Context, arg UpdateCompanyParams) error {
	_, err := q.db.Exec(ctx, updateCompany,
		arg.ID,
		arg.Name,
		arg.Industry,
		arg.Location,
		arg.EmployeeCount,
		arg.Founded,
		arg.ListingStatus,
		arg.MatchingPurpose,
	)
	return err
}

const upsertCriteria = `-- name: UpsertCriteria :exec
INSERT INTO ma_matching_criteria (company_id, purpose, revenue_min, revenue_max, ebitda_min, employee_min, employee_max, max_debt_equity_ratio, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, now())
ON CONFLICT (company_id) DO UPDATE SET
  purpose = EXCLUDED.purpose,
  revenue_min = EXCLUDED.revenue_min,
  revenue_max = EXCLUDED.revenue_max,
  ebitda_min = EXCLUDED.ebitda_min,
  employee_min = EXCLUDED.employee_min,
  employee_max = EXCLUDED.employee_max,
  max_debt_equity_ratio = EXCLUDED.max_debt_equity_ratio,
  updated_at = now()
`

type UpsertCriteriaParams struct {
	CompanyID          string
	Purpose            string
	RevenueMin         *int64
	RevenueMax         *int64
	EbitdaMin          *int64
	EmployeeMin        *int32
	EmployeeMax        *int32
	MaxDebtEquityRatio *float64
}

func (q *Queries) UpsertCriteria(ctx context.Context, arg UpsertCriteriaParams) error {
	_, err := q.db.Exec(ctx, upsertCriteria,
		arg.CompanyID,
		arg.Purpose,
		arg.RevenueMin,
		arg.RevenueMax,
		arg.EbitdaMin,
		arg.EmployeeMin,
		arg.EmployeeMax,
		arg.MaxDebtEquityRatio,
	)
	return err
}
