// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: financials.sql

package sqlcgen

import (
	"context"
	"time"
)

const getLatestFinancials = `-- name: GetLatestFinancials :one
SELECT id, company_id, fiscal_year, revenue, ebitda, net_income, total_assets, total_liabilities, equity, roe, roa, debt_equity_ratio, current_ratio, created_at
FROM ma_financials
WHERE company_id = $1
ORDER BY fiscal_year DESC
LIMIT 1
`

func (q *Queries) GetLatestFinancials(ctx context.Context, companyID string) (MaFinancial, error) {
	row := q.db.QueryRow(ctx, getLatestFinancials, companyID)
	var i MaFinancial
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.FiscalYear,
		&i.Revenue,
		&i.Ebitda,
		&i.NetIncome,
		&i.TotalAssets,
		&i.TotalLiabilities,
		&i.Equity,
		&i.Roe,
		&i.Roa,
		&i.DebtEquityRatio,
		&i.CurrentRatio,
		&i.CreatedAt,
	)
	return i, err
}

const listFinancialsByCompany = `-- name: ListFinancialsByCompany :many
SELECT id, company_id, fiscal_year, revenue, ebitda, net_income, total_assets, total_liabilities, equity, roe, roa, debt_equity_ratio, current_ratio, created_at
FROM ma_financials
WHERE company_id = $1
ORDER BY fiscal_year DESC
LIMIT $2
`

type ListFinancialsByCompanyParams struct {
	CompanyID string
	Limit     int32
}

func (q *Queries) ListFinancialsByCompany(ctx context.Context, arg ListFinancialsByCompanyParams) ([]MaFinancial, error) {
	rows, err := q.db.Query(ctx, listFinancialsByCompany, arg.CompanyID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaFinancial{}
	for rows.Next() {
		var i MaFinancial
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.FiscalYear,
			&i.Revenue,
			&i.Ebitda,
			&i.NetIncome,
			&i.TotalAssets,
			&i.TotalLiabilities,
			&i.Equity,
			&i.Roe,
			&i.Roa,
			&i.DebtEquityRatio,
			&i.CurrentRatio,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFinancials = `-- name: UpsertFinancials :one
INSERT INTO ma_financials (company_id, fiscal_year, revenue, ebitda, net_income, total_assets, total_liabilities, equity, roe, roa, debt_equity_ratio, current_ratio, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
ON CONFLICT (company_id, fiscal_year) DO UPDATE SET
  revenue = EXCLUDED.revenue,
  ebitda = EXCLUDED.ebitda,
  net_income = EXCLUDED.net_income,
  total_assets = EXCLUDED.total_assets,
  total_liabilities = EXCLUDED.total_liabilities,
  equity = EXCLUDED.equity,
  roe = EXCLUDED.roe,
  roa = EXCLUDED.roa,
  debt_equity_ratio = EXCLUDED.debt_equity_ratio,
  current_ratio = EXCLUDED.current_ratio
RETURNING id
`

type UpsertFinancialsParams struct {
	CompanyID        string
	FiscalYear       int32
	Revenue          int64
	Ebitda           int64
	NetIncome        int64
	TotalAssets      int64
	TotalLiabilities int64
	Equity           int64
	Roe              *float64
	Roa              *float64
	DebtEquityRatio  *float64
	CurrentRatio     *float64
	CreatedAt        time.Time
}

func (q *Queries) UpsertFinancials(ctx context.Context, arg UpsertFinancialsParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertFinancials,
		arg.CompanyID,
		arg.FiscalYear,
		arg.Revenue,
		arg.Ebitda,
		arg.NetIncome,
		arg.TotalAssets,
		arg.TotalLiabilities,
		arg.Equity,
		arg.Roe,
		arg.Roa,
		arg.DebtEquityRatio,
		arg.CurrentRatio,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
