// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: interests.sql

package sqlcgen

import (
	"context"
	"time"
)

const insertInterest = `-- name: InsertInterest :exec
INSERT INTO ma_interests (id, from_company_id, to_company_id, created_at) VALUES ($1, $2, $3, $4)
`

type InsertInterestParams struct {
	ID            string
	FromCompanyID string
	ToCompanyID   string
	CreatedAt     time.Time
}

func (q *Queries) InsertInterest(ctx context.Context, arg InsertInterestParams) error {
	_, err := q.db.Exec(ctx, insertInterest,
		arg.ID,
		arg.FromCompanyID,
		arg.ToCompanyID,
		arg.CreatedAt,
	)
	return err
}

const interestExists = `-- name: InterestExists :one
SELECT EXISTS (SELECT 1 FROM ma_interests WHERE from_company_id = $1 AND to_company_id = $2) AS exists
`

type InterestExistsParams struct {
	FromCompanyID string
	ToCompanyID   string
}

func (q *Queries) InterestExists(ctx context.Context, arg InterestExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, interestExists, arg.FromCompanyID, arg.ToCompanyID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listInterestsByToCompany = `-- name: ListInterestsByToCompany :many
SELECT id, from_company_id, to_company_id, created_at FROM ma_interests WHERE to_company_id = $1 ORDER BY created_at DESC, id
`

func (q *Queries) ListInterestsByToCompany(ctx context.Context, toCompanyID string) ([]MaInterest, error) {
	rows, err := q.db.Query(ctx, listInterestsByToCompany, toCompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaInterest{}
	for rows.Next() {
		var i MaInterest
		if err := rows.Scan(
			&i.ID,
			&i.FromCompanyID,
			&i.ToCompanyID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
