// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: matches.sql

package sqlcgen

import (
	"context"
	"time"
)

const getMAMatch = `-- name: GetMAMatch :one
SELECT id, company_id_a, company_id_b, score, breakdown, synergy_summary, matched_at FROM ma_matches WHERE id = $1
`

func (q *Queries) GetMAMatch(ctx context.Context, id string) (MaMatch, error) {
	row := q.db.QueryRow(ctx, getMAMatch, id)
	var i MaMatch
	err := row.Scan(
		&i.ID,
		&i.CompanyIDA,
		&i.CompanyIDB,
		&i.Score,
		&i.Breakdown,
		&i.SynergySummary,
		&i.MatchedAt,
	)
	return i, err
}

const insertMAMatch = `-- name: InsertMAMatch :exec
INSERT INTO ma_matches (id, company_id_a, company_id_b, score, breakdown, synergy_summary, matched_at) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertMAMatchParams struct {
	ID             string
	CompanyIDA     string
	CompanyIDB     string
	Score          float64
	Breakdown      []byte
	SynergySummary []byte
	MatchedAt      time.Time
}

func (q *Queries) InsertMAMatch(ctx context.Context, arg InsertMAMatchParams) error {
	_, err := q.db.Exec(ctx, insertMAMatch,
		arg.ID,
		arg.CompanyIDA,
		arg.CompanyIDB,
		arg.Score,
		arg.Breakdown,
		arg.SynergySummary,
		arg.MatchedAt,
	)
	return err
}

const listMutualMAMatchesByCompany = `-- name: ListMutualMAMatchesByCompany :many
SELECT m.id, m.company_id_a, m.company_id_b, m.score, m.breakdown, m.synergy_summary, m.matched_at
FROM ma_matches m
WHERE (m.company_id_a = $1 OR m.company_id_b = $1)
  AND EXISTS (SELECT 1 FROM ma_interests i WHERE i.from_company_id = m.company_id_a AND i.to_company_id = m.company_id_b)
  AND EXISTS (SELECT 1 FROM ma_interests i WHERE i.from_company_id = m.company_id_b AND i.to_company_id = m.company_id_a)
ORDER BY m.matched_at DESC, m.id
`

func (q *Queries) ListMutualMAMatchesByCompany(ctx context.Context, companyIDA string) ([]MaMatch, error) {
	rows, err := q.db.Query(ctx, listMutualMAMatchesByCompany, companyIDA)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaMatch{}
	for rows.Next() {
		var i MaMatch
		if err := rows.Scan(
			&i.ID,
			&i.CompanyIDA,
			&i.CompanyIDB,
			&i.Score,
			&i.Breakdown,
			&i.SynergySummary,
			&i.MatchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
