// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"
)

type DatingLike struct {
	ID         string
	FromUserID string
	ToUserID   string
	CreatedAt  time.Time
}

type DatingMatch struct {
	ID        string
	UserIDA   string
	UserIDB   string
	Score     float64
	Breakdown []byte
	MatchedAt time.Time
}

type DatingPreference struct {
	UserID    string
	AgeMin    *int32
	AgeMax    *int32
	HeightMin *int32
	HeightMax *int32
	IncomeMin *int32
	UpdatedAt time.Time
}

type DatingPreferenceDrinkingStatus struct {
	ID             int64
	UserID         string
	DrinkingStatus string
}

type DatingPreferenceEducation struct {
	ID        int64
	UserID    string
	Education string
}

type DatingPreferenceMarriageDesire struct {
	ID             int64
	UserID         string
	MarriageDesire string
}

type DatingPreferencePrefecture struct {
	ID         int64
	UserID     string
	Prefecture string
}

type DatingPreferenceSmokingStatus struct {
	ID            int64
	UserID        string
	SmokingStatus string
}

type DatingProfile struct {
	UserID           string
	Height           *int32
	BodyType         *string
	Education        *string
	Occupation       *string
	IncomeLevel      *int32
	MarriageDesire   *string
	ChildrenDesire   *string
	Smoking          *string
	Drinking         *string
	SelfIntroduction *string
	UpdatedAt        time.Time
}

type DatingProfilePhoto struct {
	ID           int64
	UserID       string
	Url          string
	IsPrimary    bool
	DisplayOrder int32
	CreatedAt    time.Time
}

type DatingProfileTag struct {
	ID     int64
	UserID string
	Tag    string
}

type DatingUser struct {
	ID           string
	Nickname     string
	Gender       string
	BirthDate    time.Time
	Prefecture   string
	Verified     bool
	EloRating    int32
	CreatedAt    time.Time
	LastActiveAt time.Time
}

type MaCompany struct {
	ID              string
	Name            string
	Industry        string
	Location        string
	EmployeeCount   int32
	Founded         time.Time
	ListingStatus   string
	MatchingPurpose string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type MaCompanyMarket struct {
	ID        int64
	CompanyID string
	Market    string
}

type MaCompanyTechnology struct {
	ID         int64
	CompanyID  string
	Technology string
}

type MaCriteriaIndustry struct {
	ID        int64
	CompanyID string
	Industry  string
}

type MaFinancial struct {
	ID               int64
	CompanyID        string
	FiscalYear       int32
	Revenue          int64
	Ebitda           int64
	NetIncome        int64
	TotalAssets      int64
	TotalLiabilities int64
	Equity           int64
	Roe              *float64
	Roa              *float64
	DebtEquityRatio  *float64
	CurrentRatio     *float64
	CreatedAt        time.Time
}

type MaInterest struct {
	ID            string
	FromCompanyID string
	ToCompanyID   string
	CreatedAt     time.Time
}

type MaMatch struct {
	ID             string
	CompanyIDA     string
	CompanyIDB     string
	Score          float64
	Breakdown      []byte
	SynergySummary []byte
	MatchedAt      time.Time
}

type MaMatchingCriterium struct {
	CompanyID          string
	Purpose            string
	RevenueMin         *int64
	RevenueMax         *int64
	EbitdaMin          *int64
	EmployeeMin        *int32
	EmployeeMax        *int32
	MaxDebtEquityRatio *float64
	UpdatedAt          time.Time
}
